// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayRiggedGames.DataAccess.Data;

#nullable disable

namespace PlayRiggedGames.DataAccess.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "eda3e09d-0aaa-4e19-984a-7b511c387a86",
                            ConcurrencyStamp = "88706e7a-ce0f-47b0-ae6d-8b8b75103018",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "e820885b-8490-4367-8bd6-50440fed5b39",
                            ConcurrencyStamp = "f8faf82d-c1a4-4ba0-ae48-1ddc66284061",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "f2672e1f-cf38-45a5-94d0-8ebb0c2ce2ce",
                            RoleId = "eda3e09d-0aaa-4e19-984a-7b511c387a86"
                        },
                        new
                        {
                            UserId = "d68aba42-86f9-45de-b529-c53869d23b1f",
                            RoleId = "e820885b-8490-4367-8bd6-50440fed5b39"
                        },
                        new
                        {
                            UserId = "d207e04f-7a11-452e-8a48-23bae4fcd12f",
                            RoleId = "e820885b-8490-4367-8bd6-50440fed5b39"
                        },
                        new
                        {
                            UserId = "b3e93844-b0c1-4e5b-a308-64353b0208d1",
                            RoleId = "e820885b-8490-4367-8bd6-50440fed5b39"
                        },
                        new
                        {
                            UserId = "0dd9ce5d-2e8d-4831-9087-7f2deab0082f",
                            RoleId = "e820885b-8490-4367-8bd6-50440fed5b39"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PlayRiggedGames.Domain.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<bool>("BlackListed")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f2672e1f-cf38-45a5-94d0-8ebb0c2ce2ce",
                            AccessFailedCount = 0,
                            Birthday = new DateTime(2000, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BlackListed = false,
                            ConcurrencyStamp = "f5e3ce66-6009-48db-a50f-126b377b42b3",
                            Email = "fuller.jc@outlook.com",
                            EmailConfirmed = true,
                            FirstName = "Jaeden",
                            LastLogin = new DateTime(2023, 5, 23, 10, 29, 28, 399, DateTimeKind.Local).AddTicks(8996),
                            LastName = "Fuller",
                            LockoutEnabled = false,
                            Money = 1000000,
                            NormalizedUserName = "ZABLOO",
                            PasswordHash = "AQAAAAEAACcQAAAAEJacxHgK8tnIdgsgeKMDRFzFwBhqR7npnWMjlCcXjOTODxV6KQnVOLUpibLLbJmWbA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aba290cd-8ece-49b0-aede-1646750292ea",
                            TwoFactorEnabled = false,
                            UserName = "ZaBloo"
                        },
                        new
                        {
                            Id = "d68aba42-86f9-45de-b529-c53869d23b1f",
                            AccessFailedCount = 0,
                            Birthday = new DateTime(1969, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BlackListed = false,
                            ConcurrencyStamp = "a64ac197-0cd3-409a-bf64-fcd5960bd0e8",
                            Email = "b.shot@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "S.",
                            LastLogin = new DateTime(2023, 5, 23, 10, 29, 28, 399, DateTimeKind.Local).AddTicks(9014),
                            LastName = "G.",
                            LockoutEnabled = false,
                            Money = 0,
                            NormalizedUserName = "NUMBER1RATEDSALESMAN1997",
                            PasswordHash = "AQAAAAEAACcQAAAAEDKAH7bqLy5NdWmv9DDda2Dc/If88AO1/tmdL17qTzNqkxrNPs2zWU+D0mNBu3hz8Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "83b6acf7-f9e9-4a8d-9311-6d27fedc22d6",
                            TwoFactorEnabled = false,
                            UserName = "number1ratedsalesman1997"
                        },
                        new
                        {
                            Id = "d207e04f-7a11-452e-8a48-23bae4fcd12f",
                            AccessFailedCount = 0,
                            Birthday = new DateTime(1995, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BlackListed = false,
                            ConcurrencyStamp = "f5988ca7-69f0-40d4-8581-084b470a7f94",
                            Email = "example@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastLogin = new DateTime(2023, 5, 23, 10, 29, 28, 399, DateTimeKind.Local).AddTicks(9024),
                            LastName = "Doe",
                            LockoutEnabled = false,
                            Money = 120,
                            NormalizedUserName = "COOLCAT12",
                            PasswordHash = "AQAAAAEAACcQAAAAECHrdkYUyPqOy+9OwgobFX4Erm2dEhDxqgE5TXzCayV1OtibQ3+DheEJqiVQjL7K9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "49771250-d469-4fe5-b9b5-9b04fa0a2085",
                            TwoFactorEnabled = false,
                            UserName = "CoolCat12"
                        },
                        new
                        {
                            Id = "b3e93844-b0c1-4e5b-a308-64353b0208d1",
                            AccessFailedCount = 0,
                            Birthday = new DateTime(1998, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BlackListed = false,
                            ConcurrencyStamp = "dc65aece-86e3-496b-8379-039b026ff5cf",
                            Email = "example@yahoo.com",
                            EmailConfirmed = true,
                            FirstName = "Samantha",
                            LastLogin = new DateTime(2023, 5, 23, 10, 29, 28, 399, DateTimeKind.Local).AddTicks(9032),
                            LastName = "Smith",
                            LockoutEnabled = false,
                            Money = 750,
                            NormalizedUserName = "LONEWOLF",
                            PasswordHash = "AQAAAAEAACcQAAAAENyngs6GihN2IedGGXK2RwOgRuPEyajGSo3+JGQjwRr2sMppzAskecQJoNsdJMIhJQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "faf60533-7bd3-4cde-a194-3181b7219114",
                            TwoFactorEnabled = false,
                            UserName = "LoneWolf"
                        },
                        new
                        {
                            Id = "0dd9ce5d-2e8d-4831-9087-7f2deab0082f",
                            AccessFailedCount = 0,
                            Birthday = new DateTime(2002, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BlackListed = false,
                            ConcurrencyStamp = "3abee90c-1f7e-4776-b07e-3fd6b9dd3dc6",
                            Email = "example@hotmail.com",
                            EmailConfirmed = true,
                            FirstName = "Veronica",
                            LastLogin = new DateTime(2023, 5, 23, 10, 29, 28, 399, DateTimeKind.Local).AddTicks(9039),
                            LastName = "Brown",
                            LockoutEnabled = false,
                            Money = 200,
                            NormalizedUserName = "GAMERGIRL123",
                            PasswordHash = "AQAAAAEAACcQAAAAEE2/sGnZ3+bD/MABOAHFsWbQrYrUz3HY+uXhD0VD4rUoaaz4rnlwk1WU5rwbsetqrw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "683a5054-b3cc-40eb-b122-03d9be8ee752",
                            TwoFactorEnabled = false,
                            UserName = "GamerGirl123"
                        });
                });

            modelBuilder.Entity("PlayRiggedGames.Domain.Models.SlotGameLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Jackpot")
                        .HasColumnType("bit");

                    b.Property<int>("MoneyInput")
                        .HasColumnType("int");

                    b.Property<int>("MoneyOutput")
                        .HasColumnType("int");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("SlotGameLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Jackpot = false,
                            MoneyInput = 50,
                            MoneyOutput = 2500,
                            PlayerId = "f2672e1f-cf38-45a5-94d0-8ebb0c2ce2ce",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3061)
                        },
                        new
                        {
                            Id = 2,
                            Jackpot = false,
                            MoneyInput = 200,
                            MoneyOutput = 8000,
                            PlayerId = "f2672e1f-cf38-45a5-94d0-8ebb0c2ce2ce",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3065)
                        },
                        new
                        {
                            Id = 3,
                            Jackpot = false,
                            MoneyInput = 150,
                            MoneyOutput = 5000,
                            PlayerId = "f2672e1f-cf38-45a5-94d0-8ebb0c2ce2ce",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3068)
                        },
                        new
                        {
                            Id = 4,
                            Jackpot = true,
                            MoneyInput = 300,
                            MoneyOutput = 15000,
                            PlayerId = "f2672e1f-cf38-45a5-94d0-8ebb0c2ce2ce",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3071)
                        },
                        new
                        {
                            Id = 5,
                            Jackpot = false,
                            MoneyInput = 1000,
                            MoneyOutput = 25000,
                            PlayerId = "f2672e1f-cf38-45a5-94d0-8ebb0c2ce2ce",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3074)
                        },
                        new
                        {
                            Id = 6,
                            Jackpot = false,
                            MoneyInput = 100,
                            MoneyOutput = 5000,
                            PlayerId = "d68aba42-86f9-45de-b529-c53869d23b1f",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3076)
                        },
                        new
                        {
                            Id = 7,
                            Jackpot = false,
                            MoneyInput = 200,
                            MoneyOutput = 10000,
                            PlayerId = "d68aba42-86f9-45de-b529-c53869d23b1f",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3079)
                        },
                        new
                        {
                            Id = 8,
                            Jackpot = false,
                            MoneyInput = 150,
                            MoneyOutput = 7500,
                            PlayerId = "d68aba42-86f9-45de-b529-c53869d23b1f",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3082)
                        },
                        new
                        {
                            Id = 9,
                            Jackpot = true,
                            MoneyInput = 300,
                            MoneyOutput = 15000,
                            PlayerId = "d68aba42-86f9-45de-b529-c53869d23b1f",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3085)
                        },
                        new
                        {
                            Id = 10,
                            Jackpot = false,
                            MoneyInput = 250,
                            MoneyOutput = 12500,
                            PlayerId = "d68aba42-86f9-45de-b529-c53869d23b1f",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3088)
                        },
                        new
                        {
                            Id = 11,
                            Jackpot = false,
                            MoneyInput = 100,
                            MoneyOutput = 5000,
                            PlayerId = "d207e04f-7a11-452e-8a48-23bae4fcd12f",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3090)
                        },
                        new
                        {
                            Id = 12,
                            Jackpot = false,
                            MoneyInput = 200,
                            MoneyOutput = 10000,
                            PlayerId = "d207e04f-7a11-452e-8a48-23bae4fcd12f",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3093)
                        },
                        new
                        {
                            Id = 13,
                            Jackpot = false,
                            MoneyInput = 150,
                            MoneyOutput = 7500,
                            PlayerId = "d207e04f-7a11-452e-8a48-23bae4fcd12f",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3096)
                        },
                        new
                        {
                            Id = 14,
                            Jackpot = true,
                            MoneyInput = 300,
                            MoneyOutput = 15000,
                            PlayerId = "d207e04f-7a11-452e-8a48-23bae4fcd12f",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3098)
                        },
                        new
                        {
                            Id = 15,
                            Jackpot = false,
                            MoneyInput = 250,
                            MoneyOutput = 12500,
                            PlayerId = "d207e04f-7a11-452e-8a48-23bae4fcd12f",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3101)
                        },
                        new
                        {
                            Id = 16,
                            Jackpot = false,
                            MoneyInput = 100,
                            MoneyOutput = 5000,
                            PlayerId = "b3e93844-b0c1-4e5b-a308-64353b0208d1",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3104)
                        },
                        new
                        {
                            Id = 17,
                            Jackpot = false,
                            MoneyInput = 200,
                            MoneyOutput = 10000,
                            PlayerId = "b3e93844-b0c1-4e5b-a308-64353b0208d1",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3106)
                        },
                        new
                        {
                            Id = 18,
                            Jackpot = false,
                            MoneyInput = 150,
                            MoneyOutput = 7500,
                            PlayerId = "b3e93844-b0c1-4e5b-a308-64353b0208d1",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3109)
                        },
                        new
                        {
                            Id = 19,
                            Jackpot = true,
                            MoneyInput = 300,
                            MoneyOutput = 15000,
                            PlayerId = "b3e93844-b0c1-4e5b-a308-64353b0208d1",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3112)
                        },
                        new
                        {
                            Id = 20,
                            Jackpot = false,
                            MoneyInput = 250,
                            MoneyOutput = 12500,
                            PlayerId = "b3e93844-b0c1-4e5b-a308-64353b0208d1",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3114)
                        },
                        new
                        {
                            Id = 21,
                            Jackpot = false,
                            MoneyInput = 100,
                            MoneyOutput = 5000,
                            PlayerId = "0dd9ce5d-2e8d-4831-9087-7f2deab0082f",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3117)
                        },
                        new
                        {
                            Id = 22,
                            Jackpot = false,
                            MoneyInput = 200,
                            MoneyOutput = 10000,
                            PlayerId = "0dd9ce5d-2e8d-4831-9087-7f2deab0082f",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3120)
                        },
                        new
                        {
                            Id = 23,
                            Jackpot = false,
                            MoneyInput = 150,
                            MoneyOutput = 7500,
                            PlayerId = "0dd9ce5d-2e8d-4831-9087-7f2deab0082f",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3122)
                        },
                        new
                        {
                            Id = 24,
                            Jackpot = true,
                            MoneyInput = 300,
                            MoneyOutput = 15000,
                            PlayerId = "0dd9ce5d-2e8d-4831-9087-7f2deab0082f",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3125)
                        },
                        new
                        {
                            Id = 25,
                            Jackpot = false,
                            MoneyInput = 250,
                            MoneyOutput = 12500,
                            PlayerId = "0dd9ce5d-2e8d-4831-9087-7f2deab0082f",
                            Time = new DateTime(2023, 5, 23, 10, 29, 28, 405, DateTimeKind.Local).AddTicks(3128)
                        });
                });

            modelBuilder.Entity("PlayRiggedGames.Domain.Models.SlotMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OutOfOrder")
                        .HasColumnType("bit");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SlotMachines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 3,
                            Name = "Lucky Slots",
                            OutOfOrder = false,
                            Width = 3
                        });
                });

            modelBuilder.Entity("PlayRiggedGames.Domain.Models.SlotOutcome", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<int>("SlotMachineId")
                        .HasColumnType("int");

                    b.Property<int>("SymbolId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "Location");

                    b.HasIndex("SymbolId");

                    b.ToTable("SlotOutcomes");
                });

            modelBuilder.Entity("PlayRiggedGames.Domain.Models.SlotSymbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlotMachineId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SlotMachineId");

                    b.ToTable("SlotSymbols");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "club",
                            SlotMachineId = 1,
                            Value = 5,
                            Weight = 50
                        },
                        new
                        {
                            Id = 2,
                            Name = "lemon",
                            SlotMachineId = 1,
                            Value = 5,
                            Weight = 50
                        },
                        new
                        {
                            Id = 3,
                            Name = "spade",
                            SlotMachineId = 1,
                            Value = 10,
                            Weight = 50
                        },
                        new
                        {
                            Id = 4,
                            Name = "banana",
                            SlotMachineId = 1,
                            Value = 10,
                            Weight = 50
                        },
                        new
                        {
                            Id = 5,
                            Name = "cherry",
                            SlotMachineId = 1,
                            Value = 10,
                            Weight = 50
                        },
                        new
                        {
                            Id = 6,
                            Name = "diamond",
                            SlotMachineId = 1,
                            Value = 15,
                            Weight = 50
                        },
                        new
                        {
                            Id = 7,
                            Name = "melon",
                            SlotMachineId = 1,
                            Value = 15,
                            Weight = 50
                        },
                        new
                        {
                            Id = 8,
                            Name = "grapes",
                            SlotMachineId = 1,
                            Value = 15,
                            Weight = 50
                        },
                        new
                        {
                            Id = 9,
                            Name = "heart",
                            SlotMachineId = 1,
                            Value = 25,
                            Weight = 50
                        },
                        new
                        {
                            Id = 10,
                            Name = "dice",
                            SlotMachineId = 1,
                            Value = 25,
                            Weight = 50
                        },
                        new
                        {
                            Id = 11,
                            Name = "chip",
                            SlotMachineId = 1,
                            Value = 25,
                            Weight = 50
                        },
                        new
                        {
                            Id = 12,
                            Name = "orange",
                            SlotMachineId = 1,
                            Value = 25,
                            Weight = 50
                        },
                        new
                        {
                            Id = 13,
                            Name = "strawberry",
                            SlotMachineId = 1,
                            Value = 25,
                            Weight = 20
                        },
                        new
                        {
                            Id = 14,
                            Name = "emerald",
                            SlotMachineId = 1,
                            Value = 50,
                            Weight = 20
                        },
                        new
                        {
                            Id = 15,
                            Name = "coin",
                            SlotMachineId = 1,
                            Value = 50,
                            Weight = 20
                        },
                        new
                        {
                            Id = 16,
                            Name = "bell",
                            SlotMachineId = 1,
                            Value = 150,
                            Weight = 10
                        },
                        new
                        {
                            Id = 17,
                            Name = "horseshoe",
                            SlotMachineId = 1,
                            Value = 150,
                            Weight = 10
                        },
                        new
                        {
                            Id = 18,
                            Name = "clover",
                            SlotMachineId = 1,
                            Value = 150,
                            Weight = 10
                        },
                        new
                        {
                            Id = 19,
                            Name = "crown",
                            SlotMachineId = 1,
                            Value = 500,
                            Weight = 3
                        },
                        new
                        {
                            Id = 20,
                            Name = "seven",
                            SlotMachineId = 1,
                            Value = 1000,
                            Weight = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PlayRiggedGames.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PlayRiggedGames.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayRiggedGames.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PlayRiggedGames.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayRiggedGames.Domain.Models.SlotGameLog", b =>
                {
                    b.HasOne("PlayRiggedGames.Domain.Models.ApplicationUser", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PlayRiggedGames.Domain.Models.SlotOutcome", b =>
                {
                    b.HasOne("PlayRiggedGames.Domain.Models.SlotGameLog", "Game")
                        .WithMany("SlotOutcomes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayRiggedGames.Domain.Models.SlotSymbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("PlayRiggedGames.Domain.Models.SlotSymbol", b =>
                {
                    b.HasOne("PlayRiggedGames.Domain.Models.SlotMachine", "SlotMachine")
                        .WithMany("Values")
                        .HasForeignKey("SlotMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SlotMachine");
                });

            modelBuilder.Entity("PlayRiggedGames.Domain.Models.SlotGameLog", b =>
                {
                    b.Navigation("SlotOutcomes");
                });

            modelBuilder.Entity("PlayRiggedGames.Domain.Models.SlotMachine", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
